### ISSUE TITLE
Blacklist-Addons - Where to get updated list

### ISSUE THREAD

**Issue by workwareusa** [prikhi/sysadmintools#1]
Prikhi, where were you getting the add-on/extension details to supplement your blacklist? I am in need of a similar list but more up to date. Appreciate any pointers on sources.

[Blocklist-addons.json](https://github.com/prikhi/sysadmintools/blob/master/office_workstation/playbook/roles/common/files/public_home/.mozilla/firefox/elh7btq7.default/blocklist-addons.json)

**Comment by prikhi** [comment]
Heya, I didn't modify that all, those are the defaults plus whatever uBlock Origin, Disconnect.me, & HTTPSEverywhere add.
